name: Docker Build & Deploy

on:
  push:
    tags:
      - '*.*-docker'
    # branches:
    #   - 'feature/deploy_to_dockerhub_issue_34'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      -
        name: dependencies
        run: |
          go mod download
      -  
        name: make test
        env:
          DOCKER_USER: ${{ secrets.docker_user }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        run: |
          export GOPATH=/home/runner/go
          export PATH="$PATH:$GOPATH/bin"
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          make test
      - 
        name: docker release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --skip-validate --config=.docker-goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.goreleaser }}